development:
  adapter: postgresql
  encoding: unicode
  database: funnycars_development
 
test:
  adapter: postgresql
  encoding: unicode
  database: funnycars_test
  
production:
  adapter: postgresql
  encoding: unicode
  database: funnycars_production
  pool: 5
  username: laurie
  password: <%= ENV["FUNNYCARS_DATABASE_PASSWORD"] %>
