# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27b7fce482696c46544cb553d21f7ea71fc65e0ac0d8560d5de7c2a45589d2ef3fdd914a53e42dc3440e11feff56ba5dd8330f70bc3c4c16b7d211cfb1487c17

test:
  secret_key_base: 0ba22b9c2b5f7fd912a2de2fbdddd7ee79fd521ae59568dfc02a1205b8c65e49f7b9bd43f883a02b78daee8b7ff8b127da62d8bcd149709aa041892b804c6001

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
